### ISSUE TITLE
decrypt image color uncorrect

### ISSUE THREAD

**Issue by 28598519a** [Anonym271/jkimouto-tools#1]
[cg077Dモ3甲.zip](https://github.com/Anonym271/jkimouto-tools/files/7979171/cg077D.3.zip)

Please see the plt sample

**Comment by Anonym271** [comment]
Your sample works for me. Could you describe your problem more specific and maybe also attach a sample of your result? (Maybe only an SFW part of it :D)

**Comment by 28598519a** [comment]
It can decrypt but the color looks strange

=> Decrypt result (uncorrect color)
![cg077Dモ3甲_00](https://user-images.githubusercontent.com/33422418/151990524-f5dec41f-9d83-4bf1-a68d-e1e7fb60e617.png)

=> It should look like that
![cg077](https://user-images.githubusercontent.com/33422418/151991041-9d949bad-6e60-48ec-b577-fa08313d9aec.png)

**Comment by Anonym271** [comment]
Okay, it seems like you were right. This sample is half transparent after my decryption and what you looking at is the half transparent image on a white background. I was looking at it in front of a black background which didn't look that weird (but was still not correct).
I tried some other samples and they are all still working. Could you find any other incorrect files so far? Because I really have no idea what could be the reason for this specific sample to fail in that way.

**Comment by 28598519a** [comment]
cg003Cモ4甲.plt
cg004Bモ3甲.plt
cg020B部5.plt
cg020B部7.plt
cg052Bモ3甲.plt
cg058Bモ4甲.plt
cg058Bモ6甲.plt
cg077Dモ3甲.plt

=> [GoogleDrive](https://drive.google.com/drive/folders/1HO8P7byS6L6XaugA4TR3433r3VKY_Te_?usp=sharing)

**Comment by 28598519a** [comment]
BTW, do you know how to get the CG Merge table definition? I think it probably define in params.dat 
[JKimou_params.zip](https://github.com/Anonym271/jkimouto-tools/files/7979647/JKimou_params.zip)

A CG is is composed of several parts  (ex: cg000 + cg000A顔1 + cg000Bモ1甲 = CG00_1) and the part XY is define in image offset 04, 08 (X, Y) ex: (0x88, 0xD8)
![](https://user-images.githubusercontent.com/33422418/151999009-97361a84-e573-48b8-a3b5-24b71fe2f9b5.png)

But what is the several parts definition? (ex: CG00_1 = A + B +C, which image is A, B, C?)

**Comment by Anonym271** [comment]
No, sorry, I didn't invest the CGs that far. This whole project was for someone who requested a tool for decrypting the PLTs on fuwanovel.

But I have some news on the questionable samples: I swapped around the colour channels in GIMP and this way I was able to correct the images. So for any reason some of the images seem to be stored with a different channel order. I will have to find out how this order is defined in the PLT file (it has to be) and then I will release a second version of the tool.

**Comment by 28598519a** [comment]
> But I have some news on the questionable samples: I swapped around the colour channels in GIMP and this way I was able to correct the images. So for any reason some of the images seem to be stored with a different channel order. I will have to find out how this order is defined in the PLT file (it has to be) and then I will release a second version of the tool.

Thanks, I'll waiting for your new version :)

**Comment by Anonym271** [comment]
Okay, I published a new release with a fix. This one should work.

Actually I was pretty stupid: those files weren't any special, it just are the only files that contain an alpha layer and my channel order for images that have an alpha channel was just completely wrong.

**Comment by 28598519a** [comment]
> Okay, I published a new release with a fix. This one should work.

Good! it works

> Actually I was pretty stupid: those files weren't any special, it just are the only files that contain an alpha layer and my channel order for images that have an alpha channel was just completely wrong.

You mean like ARGB RGBA?

===============

[Params_Tool.zip](https://github.com/Anonym271/jkimouto-tools/files/7980986/Params_Tool.zip)

Here is a program to deserialize the pararms.dat, I had pre put the params.dat of jkimouto inside. You can add break point at GameScriptParams.cs in 10xx lines

Can you use this to help me find the CGs merge rule?

**Comment by Anonym271** [comment]
> You mean like ARGB RGBA?

Yes, exactly.


> Can you use this to help me find the CGs merge rule?

I will take a look at it, but don't expect too great results. The structure seems rather complex so I will need some time to get familiar with it...

**Comment by 28598519a** [comment]
[GameScriptParams.zip](https://github.com/Anonym271/jkimouto-tools/files/7993431/GameScriptParams.zip)
=> If net 6.0, search //// delete those comment.

Done, but still thanks.

usage:
```
obj.Load(@"params.dat");
obj.DumpCgSet(@"cgSet.json");
```
